#!/usr/bin/env bash
###############################################################################
# fire-trigger.sh — Trigger #3 entry point (event-driven, PUSH model).
#
# The company is dormant until an external producer fires it. Call this at the
# end of YOUR program (training run, trading bot, CI job, ...):
#
#     .company/scripts/fire-trigger.sh training-done '{"val_bpb": 0.98}'
#
# Flow (Phase 26 Item 1 — commit state only AFTER validation/confirmation):
#   1. `--decide` — READ-ONLY. Checks the condition + the 3 base guards
#      (cooldown / dedupe / daily-cap). Never touches state.
#   2. An UNTRUSTED source runs the tool-less STAGE-1 parse; a schema-invalid
#      or require_confirm-gated payload HOLDS here having consumed NOTHING —
#      no cap slot, no cooldown/dedupe update (previously this happened AFTER
#      state was already committed, so garbage payloads burned the daily
#      budget — a trivial DoS by exactly the untrusted producer this split was
#      built to contain).
#   3. Only once the event has actually cleared validation/confirmation do we
#      `--commit`: decide+record in one flock, RE-CHECKING the guards at
#      commit time. If a racing event already won the cap/cooldown/dedupe slot
#      during the gap since step 1 (the parse may involve real work), this
#      converts the event to a clean HOLD — fail-closed, never an over-fire.
#   4. Dispatch ONE bounded, detached `claude -p` that does the work via
#      Phoebe — it does NOT block the caller.
#
# Every decision (fired or held) is appended to the trigger ledger so the
# Chairman can see what the events did.
#
# Mirrors daily-run.sh's split: deterministic decision always runs; the agent
# step is optional, time-boxed, recursion-guarded, and capped.
#
# Usage:
#   fire-trigger.sh <trigger-name> [payload-json]   # default: decide, fire if go
#   fire-trigger.sh <name> <payload> --no-spawn      # decide+record+log, no agent
#   fire-trigger.sh <name> <payload> --dry-run       # decide+log only, no state change
#   fire-trigger.sh --list                           # list user-defined triggers
###############################################################################
set -uo pipefail

PROJECT_DIR="${SELF_COMPANY_PROJECT_DIR:-$PWD}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENGINE="$SCRIPT_DIR/trigger_engine.py"
# Phase 28 Item 4b (D1): the claude-spawn scaffolding (CLAUDE_BIN resolution,
# the kill-after timeout probe, the CAPTURE_ACTIVE + `claude -p` wrapper) is
# the ONE shared lib (agent_spawn.sh, same dir) — see its header for why every
# caller keeps this exact bootstrap instead of the lib resolving its own dir.
# shellcheck source=agent_spawn.sh
source "$SCRIPT_DIR/agent_spawn.sh"

# A .company may sit at $PWD/.company (used) or be the script's parent (dev).
if [[ -d "$PROJECT_DIR/.company" ]]; then COMPANY="$PROJECT_DIR/.company"
elif [[ "$(basename "$(dirname "$SCRIPT_DIR")")" == ".company" ]]; then COMPANY="$(dirname "$SCRIPT_DIR")"
else COMPANY="$PROJECT_DIR/.company"; fi

NAME="${1:-}"; shift || true
if [[ "$NAME" == "--list" ]]; then
  python3 "$ENGINE" --company "$COMPANY" --list
  exit 0
fi
PAYLOAD="{}"; SPAWN=true; RECORD=true; EMIT=false; DRYRUN=false
for a in "$@"; do
  case "$a" in
    --no-spawn)    SPAWN=false ;;
    --dry-run)     SPAWN=false; RECORD=false; DRYRUN=true ;;
    --emit-prompt) EMIT=true ;;   # build+print the dispatch prompt, no state, no spawn (tests)
    -*)            : ;;
    *)             PAYLOAD="$a" ;;
  esac
done
# --emit-prompt is a pure diagnostic: never mutate trigger state.
$EMIT && RECORD=false

if [[ -z "$NAME" ]]; then
  echo "usage: fire-trigger.sh <trigger-name> [payload-json] [--no-spawn|--dry-run]" >&2
  exit 2
fi

LOGDIR="$COMPANY/ops/logs"; REPORTS="$COMPANY/ops/reports"
mkdir -p "$LOGDIR" "$REPORTS"
DATE="$(date +%F)"; TS="$(date +%FT%T)"
LEDGER="$REPORTS/triggers.md"

ledger_row() {  # ts | trigger | fired/held | reason | payload(short)
  $EMIT && return 0
  [[ -f "$LEDGER" ]] || printf '# Trigger Ledger\n\n_One row per fire-trigger.sh call. Generated by the event trigger (#3)._\n\n| time | trigger | result | reason | payload |\n|---|---|---|---|---|\n' > "$LEDGER"
  local short="${PAYLOAD:0:60}"
  printf '| %s | %s | %s | %s | `%s` |\n' "$TS" "$NAME" "$1" "${REASON//_/ }" "$short" >> "$LEDGER"
}

# 1. DECIDE — READ-ONLY (Item 1). Only the condition + the 3 base guards
#    (cooldown/dedupe/daily-cap); mirrors exactly what `decide()` checks and
#    NEVER mutates state. Commit is deferred to step 3, after STAGE-1 parse /
#    schema validation / require_confirm resolve.
DECISION="$(python3 "$ENGINE" --company "$COMPANY" --trigger "$NAME" --payload "$PAYLOAD" --decide 2>/dev/null)"
read -r FIRE REASON ACTION BUDGET TRUST CONFIRM <<<"$(python3 - "$DECISION" <<'PY'
import json, sys
d = json.loads(sys.argv[1]) if sys.argv[1] else {}
print(str(d.get("fire", False)).lower(),
      str(d.get("reason", "?")).replace(" ", "_"),
      "ok" if d.get("action") else "noaction",
      d.get("budget", 0),
      d.get("source_trust", "untrusted"),
      str(d.get("require_confirm", False)).lower())
PY
)"

if [[ "$FIRE" != "true" ]]; then
  ledger_row "held"
  echo "[fire-trigger] held: $NAME ($REASON)"
  exit 0
fi

# 2. require_confirm gate — applies REGARDLESS of source_trust (GIB re-attack
#    MUST-FIX 1). This is the highest-risk gate (the money-moving "payout"
#    example is itself a TRUSTED trigger); trust only gates the parse->act
#    two-stage path below, NEVER the confirm gate. Item 2 (Elon: option b):
#    require_confirm is a deterministic HOLD-for-manual, not an approval queue
#    — no state consumed, no pending-file artifact. A real approval workflow
#    (queue + list + resolve + notify) is a later, separate feature. There is
#    deliberately NO recovery flag today (an advertised `--confirm-override`
#    that silently no-ops would be worse than none) — the honest message says
#    exactly what is and isn't there.
if [[ "$CONFIRM" == "true" ]]; then
  REASON="require_confirm"; ledger_row "held"
  echo "[fire-trigger] held: require_confirm — held for manual dispatch; approval workflow planned (no auto-dispatch): $NAME"
  exit 0
fi

# 2b. UNTRUSTED sources: the tool-less STAGE-1 parse runs BEFORE any state is
#    touched (Item 4's privilege separation, now correctly ordered ahead of
#    commit — Item 1). Anything off-schema HOLDS having consumed NOTHING: no
#    cap slot, no cooldown/dedupe update, no artifact on disk.
if [[ "$TRUST" == "untrusted" ]]; then
  PARSE="$(python3 "$ENGINE" --company "$COMPANY" --trigger "$NAME" --payload "$PAYLOAD" --parse-intent 2>/dev/null)"
  PARSE_OK="$(python3 - "$PARSE" <<'PY'
import json, sys
try:
    d = json.loads(sys.argv[1]) if sys.argv[1] else {}
except Exception:
    d = {}
print("true" if d.get("ok") else "false")
PY
)"
  if [[ "$PARSE_OK" != "true" ]]; then
    HOLD_REASON="$(python3 - "$PARSE" <<'PY'
import json, sys
try:
    d = json.loads(sys.argv[1]) if sys.argv[1] else {}
except Exception:
    d = {}
print(str(d.get("reason", "schema validation failed")))
PY
)"
    REASON="held_schema"; ledger_row "held"
    echo "[fire-trigger] held (schema): $NAME ($HOLD_REASON)"
    exit 0
  fi
fi

# 3. COMMIT — only now, after the event has actually cleared validation and
#    confirmation, do we touch state. `--commit` re-decides UNDER THE STATE
#    LOCK (the TOCTOU re-check): if a racing event already claimed the
#    cap/cooldown/dedupe slot in the gap since step 1 (the parse above may
#    involve real work), this converts the event to a clean HOLD — fail-
#    closed, never an over-fire. --dry-run / --emit-prompt (RECORD=false)
#    never commit.
if $RECORD; then
  COMMIT="$(python3 "$ENGINE" --company "$COMPANY" --trigger "$NAME" --payload "$PAYLOAD" --commit 2>/dev/null)"
  read -r CFIRE CREASON <<<"$(python3 - "$COMMIT" <<'PY'
import json, sys
d = json.loads(sys.argv[1]) if sys.argv[1] else {}
print(str(d.get("fire", False)).lower(), str(d.get("reason", "?")).replace(" ", "_"))
PY
)"
  if [[ "$CFIRE" != "true" ]]; then
    REASON="$CREASON"; ledger_row "held"
    echo "[fire-trigger] held: $NAME ($REASON)"
    exit 0
  fi
fi

# 4. DISPATCH decision. No agent when --no-spawn/--dry-run (state is already
#    committed for --no-spawn; --dry-run never committed anything above).
if ! $SPAWN; then
  ledger_row "fired"
  if $DRYRUN; then
    echo "[fire-trigger] fired (dry-run): $NAME"
  else
    echo "[fire-trigger] fired (no-spawn): $NAME"
  fi
  exit 0
fi

if ! $EMIT; then
  CLAUDE_BIN="$(sc_resolve_claude_bin)"
  if [[ -z "$CLAUDE_BIN" ]]; then
    ledger_row "fired"
    echo "[fire-trigger] fired but claude CLI not found — logged only: $NAME"
    exit 0
  fi
fi

AGENT_LOG="$LOGDIR/trigger-$DATE.log"
ACTION_TEXT="$(python3 - "$DECISION" <<'PY'
import json, sys
print(json.loads(sys.argv[1]).get("action", ""))
PY
)"

# Phase 29 Item 4 (Bob P1, shared prompt_builder.py): the REAL bound is
# wall-clock SECONDS (the `timeout` wrapper below), never tokens — a headless
# CLI worker has no usage counter to pace against. $TRIGGER_BUDGET_SECONDS is
# the SAME variable the spawn call receives later, so the stated budget and
# the actual kill deadline can never drift apart. The old "Stay within
# roughly $BUDGET tokens" sentence is gone — a CLI worker cannot observe it.
TRIGGER_BUDGET_SECONDS="${SELF_COMPANY_TRIGGER_TIMEOUT:-600}"
BUDGET_LINE="$(python3 "$SCRIPT_DIR/prompt_builder.py" budget --seconds "$TRIGGER_BUDGET_SECONDS")"
CONTRACT_LINE="$(python3 "$SCRIPT_DIR/prompt_builder.py" contract \
  --where ".company/ops/logs/trigger-$DATE.log" \
  --format "a one-line note of what you did")"
BOUNDARY_LINE="$(python3 "$SCRIPT_DIR/prompt_builder.py" boundary \
  --text "route through Phoebe (the execution gateway), plan the minimal work, and keep it tight; if the data below doesn't actually warrant work, note that and stop")"

# 5. ROUTE by source_trust (Item 4 — parse->act privilege separation).
if [[ "$TRUST" == "trusted" ]]; then
  # TRUSTED internal trigger: direct path (Chairman-approved). The raw payload
  # is interpolated but fenced with a PER-CALL RANDOM NONCE (Phase 29 Item 4
  # P2 fix — a static `===== BEGIN X =====` delimiter can be escaped by a
  # payload that happens to contain that literal string; mirrors
  # trigger_engine.fence_payload as defence-in-depth).
  ROLE_LINE="$(python3 "$SCRIPT_DIR/prompt_builder.py" role \
    --name "the self-company EVENT TRIGGER agent" \
    --role "TRUSTED internal source, fired non-interactively, no human present")"
  FENCE_BLOCK="$(python3 "$SCRIPT_DIR/prompt_builder.py" fence \
    --data "$PAYLOAD" --label "UNTRUSTED PAYLOAD")"
  read -r -d '' PROMPT <<EOF || true
$ROLE_LINE Working dir: $PROJECT_DIR.
$BUDGET_LINE
Trigger: $NAME
Requested action: $ACTION_TEXT

$FENCE_BLOCK

$CONTRACT_LINE
$BOUNDARY_LINE
EOF
else
  # UNTRUSTED source: two-stage, privilege-separated. STAGE 1 already ran in
  # step 2 above ($PARSE holds the schema-validated intent) — STAGE 2 ACT
  # consumes ONLY that validated intent. The raw $PAYLOAD string is NEVER
  # interpolated into this prompt.
  INTENT_JSON="$(python3 - "$PARSE" <<'PY'
import json, sys
print(json.dumps(json.loads(sys.argv[1])["intent"], ensure_ascii=False))
PY
)"
  SUMMARY="$(python3 - "$PARSE" <<'PY'
import json, sys
print(json.loads(sys.argv[1])["intent"].get("summary", ""))
PY
)"
  ROLE_LINE="$(python3 "$SCRIPT_DIR/prompt_builder.py" role \
    --name "the self-company EVENT TRIGGER agent" \
    --role "fired non-interactively by an external UNTRUSTED event, no human present")"
  FENCE_BLOCK="$(python3 "$SCRIPT_DIR/prompt_builder.py" fence \
    --data "$(printf 'summary: %s\nfields: %s' "$SUMMARY" "$INTENT_JSON")" \
    --label "SANITIZED INTENT")"
  read -r -d '' PROMPT <<EOF || true
$ROLE_LINE Working dir: $PROJECT_DIR.
$BUDGET_LINE

A privilege-separated PARSE stage has already reduced the raw event payload to a
small, schema-validated intent: only sanitized scalar fields survive, and the
action below comes from the TRUSTED trigger definition, NOT the payload.
Trigger: $NAME
Requested action: $ACTION_TEXT

$FENCE_BLOCK

$CONTRACT_LINE
$BOUNDARY_LINE
EOF
fi

# --emit-prompt: print the built dispatch prompt and stop (no ledger, no spawn).
if $EMIT; then
  printf '%s\n' "$PROMPT"
  exit 0
fi

ledger_row "fired"

# Detached + time-boxed + recursion-guarded (so the CAPTURE Stop hook no-ops).
# Item 1 (TOM-2): hard-kill grace. This spawn is DETACHED (nohup … &), so a claude
# that traps SIGTERM would otherwise survive its budget as an unreaped orphan with
# nothing watching it. `timeout -k <grace>` SIGKILLs it <grace>s past budget. `-k`
# is GNU coreutils; degrade to a plain SIGTERM timeout where unsupported.
printf '\n===== trigger %s fired %s =====\n' "$NAME" "$TS" >> "$AGENT_LOG"
KILL_AFTER="${SELF_COMPANY_TIMEOUT_KILL_AFTER:-30}"
# Phase 29 Item 2: default model resolves through schedule_config's ONE
# source-of-truth constant (DEFAULT_AGENT_MODEL) instead of a second
# hardcoded literal here — env override still wins.
_default_model="$(python3 "$SCRIPT_DIR/schedule_config.py" --company "$COMPANY" \
  --agent model 2>/dev/null || true)"
[[ -n "$_default_model" ]] || _default_model="claude-sonnet-5"
# $TRIGGER_BUDGET_SECONDS is the SAME value the prompt's budget_line stated
# above — one source, so the stated budget and the real kill deadline agree.
sc_spawn_capture "$KILL_AFTER" "$TRIGGER_BUDGET_SECONDS" "$CLAUDE_BIN" \
  "$PROMPT" "${SELF_COMPANY_TRIGGER_MODEL:-$_default_model}"
nohup "${SC_SPAWN_CMD[@]}" >>"$AGENT_LOG" 2>&1 &
echo "[fire-trigger] fired: $NAME -> dispatched (detached, see ops/logs/trigger-$DATE.log)"
exit 0
