#!/usr/bin/env python3
"""
elon_survey — Elon's daily CEO survey + prioritized TODO list.

So the CEO is load-bearing every day (not just when addressed): this surveys the
company's real state (entropy, decay/promotion candidates, verification gaps, tier
distribution) and writes a PRIORITIZED todo list to ops/plans/todo-<date>.md. It
is deterministic and read-only over memory (runs decay/verify in dry-run); it does
NOT mutate memory or the skeleton — pure direction-setting.

Usage: elon_survey.py [--company DIR] [--now YYYY-MM-DD]
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import date
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent


def _run_json(script, *args):
    p = SCRIPTS / script
    if not p.exists():
        return None
    try:
        out = subprocess.run([sys.executable, str(p), *args],
                             capture_output=True, text=True, timeout=120).stdout
        return json.loads(out)
    except Exception:
        return None


def tier_counts(memory_dir):
    counts = {"L0": 0, "L1": 0, "L2": 0}
    base = Path(memory_dir)
    for tier, sub in (("L0", "L0-working"), ("L1", "L1-warm"), ("L2", "L2-cold")):
        d = base / sub
        if d.exists():
            counts[tier] = sum(1 for _ in d.rglob("*.md"))
    return counts


def build_todos(entropy, decay, verify):
    """Rule-based prioritized todo list. Returns list of (priority, text)."""
    todos = []
    if entropy:
        det = entropy.get("details", {})
        contra = det.get("contradiction_pairs", [])
        if contra:
            todos.append((1, f"Adjudicate {len(contra)} contradiction candidate(s) "
                             f"(Tony): {contra[:4]}"))
        dups = det.get("duplicate_pairs", [])
        if dups:
            todos.append((4, f"Dedup {len(dups)} near-duplicate pair(s): {dups[:4]}"))
        stale = det.get("stale_ids", [])
        if stale:
            todos.append((5, f"Review {len(stale)} stale memory(ies): {stale[:6]}"))
        ent = entropy.get("entropy", 0)
        if ent and ent > 0.3:
            todos.append((2, f"Entropy elevated ({ent}) — schedule a deep-clean pass"))
    if verify:
        unver = verify.get("unverifiable", [])
        if unver:
            todos.append((3, f"Re-capture/confirm {len(unver)} memory(ies) whose sources "
                             f"don't trace: {unver[:6]}"))
    if decay:
        uc = decay.get("actions", {}).get("upgrade_candidates", [])
        if uc:
            todos.append((3, f"Promote {len(uc)} reinforced memory(ies): "
                             f"{[c['id'] for c in uc][:6]}"))
        demote = decay.get("actions", {}).get("demote", [])
        if demote:
            todos.append((6, f"{len(demote)} L1 memory(ies) gone cold — demotion pending"))
    todos.sort(key=lambda t: t[0])
    return todos


def survey(company, today):
    mem = str(Path(company) / "memory")
    policy = str(Path(company) / "org" / "policy.md")
    entropy = _run_json("entropy.py", "--memory-dir", mem, "--config", policy, "--now", today)
    decay = _run_json("decay.py", "--memory-dir", mem, "--config", policy, "--now", today)
    verify = _run_json("verify_memory.py", "--memory-dir", mem,
                       "--transcripts-dir", os.path.expanduser("~/.claude/projects"),
                       "--now", today)
    tiers = tier_counts(mem)
    todos = build_todos(entropy, decay, verify)

    lines = [f"# Elon — Daily Survey & TODO ({today})", ""]
    ent = entropy.get("entropy") if entropy else "?"
    dims = entropy.get("dimensions", {}) if entropy else {}
    lines.append(f"**Health:** entropy {ent} | memory L0={tiers['L0']} L1={tiers['L1']} "
                 f"L2={tiers['L2']} | unverified_rate {dims.get('unverified_rate', '?')}")
    lines.append("")
    lines.append("## TODO (priority order)")
    if todos:
        for i, (_, text) in enumerate(todos, 1):
            lines.append(f"{i}. {text}")
    else:
        lines.append("1. Company healthy — no action needed. Keep capturing.")
    lines.append("")
    lines.append("_Generated by Elon's daily survey (read-only; deterministic)._")
    return "\n".join(lines) + "\n", {"entropy": ent, "tiers": tiers, "todos": len(todos)}


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--company", default=".company")
    ap.add_argument("--now", default=None)
    args = ap.parse_args(argv)
    today = args.now or date.today().isoformat()
    company = args.company
    if not Path(company).exists():
        print(json.dumps({"error": "no .company", "todos": 0}))
        return 0
    text, summary = survey(company, today)
    plans = Path(company) / "ops" / "plans"
    plans.mkdir(parents=True, exist_ok=True)
    out = plans / f"todo-{today}.md"
    out.write_text(text, encoding="utf-8")
    summary["written"] = str(out)
    print(json.dumps(summary, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
