#!/usr/bin/env bash
###############################################################################
# fire-trigger.sh — Trigger #3 entry point (event-driven, PUSH model).
#
# The company is dormant until an external producer fires it. Call this at the
# end of YOUR program (training run, trading bot, CI job, ...):
#
#     .company/scripts/fire-trigger.sh training-done '{"val_bpb": 0.98}'
#
# Flow: ask the deterministic engine whether to fire (condition + 3 guards:
# cooldown / dedupe / daily-cap). If yes, stamp state and launch ONE bounded,
# detached `claude -p` that does the dispatched work via Phoebe — it does NOT
# block the caller. Every decision (fired or held) is appended to the trigger
# ledger so the Chairman can see what the events did.
#
# Mirrors daily-run.sh's split: deterministic decision always runs; the agent
# step is optional, time-boxed, recursion-guarded, and capped.
#
# Usage:
#   fire-trigger.sh <trigger-name> [payload-json]   # default: decide, fire if go
#   fire-trigger.sh <name> <payload> --no-spawn      # decide+record+log, no agent
#   fire-trigger.sh <name> <payload> --dry-run       # decide+log only, no state change
#   fire-trigger.sh --list                           # list user-defined triggers
###############################################################################
set -uo pipefail

PROJECT_DIR="${SELF_COMPANY_PROJECT_DIR:-$PWD}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENGINE="$SCRIPT_DIR/trigger_engine.py"

# A .company may sit at $PWD/.company (used) or be the script's parent (dev).
if [[ -d "$PROJECT_DIR/.company" ]]; then COMPANY="$PROJECT_DIR/.company"
elif [[ "$(basename "$(dirname "$SCRIPT_DIR")")" == ".company" ]]; then COMPANY="$(dirname "$SCRIPT_DIR")"
else COMPANY="$PROJECT_DIR/.company"; fi

NAME="${1:-}"; shift || true
if [[ "$NAME" == "--list" ]]; then
  python3 "$ENGINE" --company "$COMPANY" --list
  exit 0
fi
PAYLOAD="{}"; SPAWN=true; RECORD=true
for a in "$@"; do
  case "$a" in
    --no-spawn) SPAWN=false ;;
    --dry-run)  SPAWN=false; RECORD=false ;;
    -*)         : ;;
    *)          PAYLOAD="$a" ;;
  esac
done

if [[ -z "$NAME" ]]; then
  echo "usage: fire-trigger.sh <trigger-name> [payload-json] [--no-spawn|--dry-run]" >&2
  exit 2
fi

LOGDIR="$COMPANY/ops/logs"; REPORTS="$COMPANY/ops/reports"
mkdir -p "$LOGDIR" "$REPORTS"
DATE="$(date +%F)"; TS="$(date +%FT%T)"
LEDGER="$REPORTS/triggers.md"

# 1. DECIDE (deterministic; never spawns)
DECISION="$(python3 "$ENGINE" --company "$COMPANY" --trigger "$NAME" --payload "$PAYLOAD" --decide 2>/dev/null)"
read -r FIRE REASON ACTION BUDGET <<<"$(python3 - "$DECISION" <<'PY'
import json, sys
d = json.loads(sys.argv[1]) if sys.argv[1] else {}
print(str(d.get("fire", False)).lower(), d.get("reason", "?").replace(" ", "_"),
      "ok" if d.get("action") else "noaction", d.get("budget", 0))
PY
)"

ledger_row() {  # ts | trigger | fired/held | reason | payload(short)
  [[ -f "$LEDGER" ]] || printf '# Trigger Ledger\n\n_One row per fire-trigger.sh call. Generated by the event trigger (#3)._\n\n| time | trigger | result | reason | payload |\n|---|---|---|---|---|\n' > "$LEDGER"
  local short="${PAYLOAD:0:60}"
  printf '| %s | %s | %s | %s | `%s` |\n' "$TS" "$NAME" "$1" "${REASON//_/ }" "$short" >> "$LEDGER"
}

if [[ "$FIRE" != "true" ]]; then
  ledger_row "held"
  echo "[fire-trigger] held: $NAME ($REASON)"
  exit 0
fi

# 2. RECORD the fire (cooldown/dedupe/cap state) unless --dry-run
$RECORD && python3 "$ENGINE" --company "$COMPANY" --trigger "$NAME" --payload "$PAYLOAD" --record >/dev/null 2>&1
ledger_row "fired"

# 3. DISPATCH: one bounded, detached agent (does not block the caller)
if ! $SPAWN; then
  echo "[fire-trigger] fired (no-spawn): $NAME"
  exit 0
fi

CLAUDE_BIN="$(command -v claude || true)"
[[ -z "$CLAUDE_BIN" && -x "$HOME/.local/bin/claude" ]] && CLAUDE_BIN="$HOME/.local/bin/claude"
if [[ -z "$CLAUDE_BIN" ]]; then
  echo "[fire-trigger] fired but claude CLI not found — logged only: $NAME"
  exit 0
fi

ACTION_TEXT="$(python3 - "$DECISION" <<'PY'
import json, sys
print(json.loads(sys.argv[1]).get("action", ""))
PY
)"
AGENT_LOG="$LOGDIR/trigger-$DATE.log"
read -r -d '' PROMPT <<EOF || true
You are the self-company EVENT TRIGGER agent, fired non-interactively by an
external event (no human present). Working dir: $PROJECT_DIR.
Trigger: $NAME
Payload: $PAYLOAD
Requested action: $ACTION_TEXT

Route this through Phoebe (the execution gateway): plan the minimal work, dispatch
it, and keep it tight. Stay within roughly $BUDGET tokens. Append a one-line note
of what you did to .company/ops/logs/trigger-$DATE.log. If the payload doesn't
actually warrant work, note that and stop.
EOF

# Detached + time-boxed + recursion-guarded (so the CAPTURE Stop hook no-ops).
printf '\n===== trigger %s fired %s =====\n' "$NAME" "$TS" >> "$AGENT_LOG"
SELF_COMPANY_CAPTURE_ACTIVE=1 nohup timeout "${SELF_COMPANY_TRIGGER_TIMEOUT:-600}" \
  "$CLAUDE_BIN" -p "$PROMPT" --model "${SELF_COMPANY_TRIGGER_MODEL:-claude-sonnet-4-6}" \
  >>"$AGENT_LOG" 2>&1 &
echo "[fire-trigger] fired: $NAME -> dispatched (detached, see ops/logs/trigger-$DATE.log)"
exit 0
